
const:
  default-page-size: 20
  auth-code-length: 6

file:
  directory: D:/mydownload/greengram_ver3

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: email1
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/ca2sa
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ungjae1322
    password: qbotybwuiincfasg
    properties:
      mail:
        smtp:
          auth: true  # SMTP ?? ??
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    path: /swagger
    operations-sorter: method
    tags-sorter: alpha
  cache:
    disabled: true